//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    
    public partial class GetArticulosByArea
    {
        public int ArticulosID { get; set; }
        public Nullable<int> AreasID { get; set; }
        public string ArticulosDescrip { get; set; }
        public Nullable<int> Baja { get; set; }
    }
}
