//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    
    public partial class GetPedidosCerrados
    {
        public Nullable<int> NroPedidoReparacion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaPasaTecnico { get; set; }
        public Nullable<System.DateTime> FechaTomaTecnico { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Cliente { get; set; }
        public string tecnico { get; set; }
    }
}
