//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    
    public partial class GetPedidosBYtecnicoID
    {
        public Nullable<int> NroPedidoReparacion { get; set; }
        public int PedidoReparacionID { get; set; }
        public string Cliente { get; set; }
        public string Articulo { get; set; }
        public string Domicilio { get; set; }
        public string Problema { get; set; }
        public string Horario { get; set; }
    }
}
