//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    
    public partial class GetRetirosDisponibles
    {
        public int PedidoRetiradoID { get; set; }
        public Nullable<int> NroPedidoRetirado { get; set; }
    }
}
