//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoReparacionDetalle
    {
        public int PedidoReparacionDetalleID { get; set; }
        public int ArticuloID { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> AreasID { get; set; }
    }
}
