//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Clases.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoReparacion
    {
        public int PedidoReparacionID { get; set; }
        public Nullable<int> PedidoReparacionDetalleID { get; set; }
        public Nullable<int> NroPedidoReparacion { get; set; }
        public int DomiclioID { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string DescripcionProblema { get; set; }
        public string HorarioDisponible { get; set; }
        public Nullable<System.DateTime> FechaPasaTecnico { get; set; }
        public Nullable<System.DateTime> FechaTomaTecnico { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
